---
title: "Result Presentation"
lang: en-EN
output:
  word_document: default
  pdf_document:
    keep_tex: yes
editor_options:
  chunk_output_type: console
---


```{r, include=FALSE}
library(dplyr)
library(memisc)
library(haven)
library(lmtest)
library(ggplot2)
library(ggfortify)
library(pander)
library(lme4)
library(ggpubr)
library(car)
library(sandwich)
library(ggthemes)
library(Hmisc)
library(huxtable)

df = as.data.frame(read_spss("BD final - estudantes.sav"))

dataF = transmute(df, oportunidade = as.numeric(df$tri_oportunidade),
                  pressao = as.numeric(df$losango_motivacao),
                  racionalizacao = as.numeric(df$tri_dist_moral),
                  fraudenavg = rowMeans(df[68:71], na.rm = TRUE),
                  kgavg = as.factor(as.integer(rowMeans(df[51:67], na.rm = TRUE))),
                  kfavg = rowMeans(df[34:50], na.rm = TRUE))

ModelN = lm(data = dataF, fraudenavg ~ oportunidade + pressao + racionalizacao)

ModelC = lm(data = dataF, kfavg ~ oportunidade + pressao + racionalizacao + kgavg)
```

```{r, results='asis', warning=FALSE}
#1st Graph
ggplot(ModelC) + stat_qq(aes(sample = ModelC$residuals), color = "black", alpha = 0.2) + geom_abline(intercept = mean(ModelC$residuals), slope = sd(ModelC$residuals), color = "red") + theme_calc()

#2nd Graph
ggplot(ModelC, aes(x = .resid, y = ..density..)) + geom_histogram(bins = 15, color = "white", fill = "black") + theme_calc()

#3rd Graph
ggplot(ModelN, aes(x = .fitted, y = .resid)) + geom_point(color = "black", alpha = 0.3) + stat_smooth(color = "red") + theme_calc()


reg_table <- huxreg(ModelN, ModelC, statistics = c(N = "nobs", R2 = "r.squared", R2Adj = "adj.r.squared", 
  "AIC"))
print_md(reg_table)
```



